# Uncomment the next line to define a global platform for your project
platform :ios, '18.0'

target 'driver_frontend' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps', '~> 9.0'
  pod 'Google-Maps-iOS-Utils', '~> 6.1'

end
